### ISSUE TITLE
Merge Cliques in "Concept by text" search table

### ISSUE THREAD

**Issue by RichardBruskiewich** [NCATS-Tangerine/tkbio#64] opened 2017-12-18 20:42 UTC
The concept table popup window that returns matches for key word searches presents matches of identifiers form all sources, without merging the entries by clique. Clearly, presenting one row entry per clique would make more sense; however, some way of restructuring the presentation of the output is necessary, to still present to the user all matching identifiers indexed by their beacon source.

Note that presenting all matches may be challenging due to the number of equivalent identifiers in a given clique (maybe need to create a new popup window of some kind which presents the aliases in a structured fashion...)

**Comment by lhannest** [comment] 2018-06-04 16:11
First part of the issue is resolved, as now only cliques are returned through the API. Creating a new issue https://github.com/NCATS-Tangerine/tkbio/issues/72 and closing this one.

**Closed by lhannest** 2018-06-04 16:11 UTC
